gois_list <- list(
  bra.down = c("Msgn1", "Osr1", "Rspo3", "Fgf8", "Wnt3a"),
  eo.down = c("Mesp1", "Foxa2", "Sox17", "Lhx1", "Cer1"),
  eo.down.repr = c("Dmdx1", "Dpf3", "Foxa1", "Hey1", "Hhex", "Tcf7l2", "Tle2"),
  pp.up = c("Lefty1", "Lefty2", "Nodal", "Wnt8a", "Fgf5", "Otx2", "Cldn6"),
  episc.up = c("Nanog", "Pou5f1", "Sox2", "L1td1", "Utf1"),
  ne.up = c("Sox1", "Sox3", "Olig3", "Gbx2", "Pou3f1", "Msx3", "Slc7a3",
            "Zic1", "Zic2", "Nkx1-2", "Epha2", "Efnb1", "Nkx6-2"),
  me.down = c("Pdgfra", "Foxc1", "Foxc2", "Isl1", "Kdr",
              "Mixl1", "Hand1", "Myh6"),
  hox.genes = c("Hoxa1", "Hoxa10", "Hoxa11", "Hoxa11os", "Hoxa13", "Hoxa2",
                "Hoxa3", "Hoxa4", "Hoxa5", "Hoxa6", "Hoxa7", "Hoxa9", "Hoxaas2",
                "Hoxaas3", "Hoxb1", "Hoxb13", "Hoxb2", "Hoxb3", "Hoxb3os",
                "Hoxb4", "Hoxb5", "Hoxb5os", "Hoxb6", "Hoxb7", "Hoxb8", "Hoxb9",
                "Hoxc10", "Hoxc11", "Hoxc12", "Hoxc13", "Hoxc4", "Hoxc5",
                "Hoxc6", "Hoxc8", "Hoxc9", "Hoxd1", "Hoxd10", "Hoxd11",
                "Hoxd12", "Hoxd13", "Hoxd3", "Hoxd3os1", "Hoxd4", "Hoxd8",
                "Hoxd9"),
  main.genes = c("T", "Eomes", "Wnt3", "Wnt3a", "Nodal", "Fgf8", "Mixl1",
                 "EGFP"),
  ac.1 = c("Fgf8", "Eomes", "Foxa2", "Meis1", "Otx2", "Lhx1",
           "Mixl1", "Cyp26a1", "T", "Cdx1", "Cdx2", "Axin2", "Rspo3", "Wnt3a"),
  ac.2 = c("Axin2", "Cdx1", "Cdx2", "Cyp26a1", "Dkk1", "Meis1", "Mesp1"),
  other1 = c("Foxc2", "Gsc", "Mixl1", "Foxc1", "Pdgfra", "Kdr", "Tbx1",
             "Amot", "Eya1", "Prrx1", "Lhx1", "Tnnt1", "Isl1", "Tbx20",
             "Myh7", "Myh6", "Eya2", "Tbx18", "Snai1", "Snai2", "Hand1",
             "Hand2", "Mesp1", "Pax2", "Mesp2", "Col2a1", "Myocd", "Pax3",
             "Wt1", "Dll3", "Prickle1", "Msgn1", "Rspo3", "Osr1", "Twist1",
             "Twist2", "Tbx6", "Meox1", "Gata6", "Gata4", "Foxa2", "Sox17",
             "Lama1", "Tgfa", "Fn1", "Cer1", "Tgfb2", "Bmper", "Chrd", "Lgr5",
             "Bmp2", "Fzd7", "Wnt3a", "Bmp7", "Cfc1", "Dkk1", "Fgf1",
             "Tdgf1", "Wnt3", "Tgfb1", "Nodal", "Dact1", "Bmp4", "Dll1",
             "Hey1", "Hhex", "Id1", "Dmbx1", "Dpf3", "Sall1", "Foxa1",
             "Tcf7l2", "Hesx1", "Tcf7l1", "Hdac7", "Otx2", "Fbn2", "Otx1"),
  other2 <- c("Six3", "Fabp7", "Ntrk2", "Zic1", "Mab21l2", "Nefl", "Olig3",
              "Pou4f2", "Nkx1-2", "Sox3", "Sema3c", "Epha2", "Zic3", "Efnb1",
              "Radil", "Syt11", "Slc7a3", "Nes", "Zic5", "Snph", "Nfasc",
              "Pou4f1", "Elavl3", "Nrcam", "Grin1", "Gfra3", "Phox2a", "Nkx6-2",
              "Pax6", "Nsg2", "Msx3", "Ephb1", "Ncan", "Nova2", "Zic2", "Grik3",
              "Epha1", "Bcl11a", "Hoxa2", "Tubb3", "Sox1", "Neurod1", "Neurog1",
              "Stmn2", "Atxn1", "Cntn2", "Neurl1a", "Sema3c", "Gap43", "Fgf5",
              "Tbx3", "Cldn6", "Pou3f1", "Lefty2", "Gbx2", "Nanog", "L1td1",
              "Wnt8a", "Pou5f1", "Lefty1", "Utf1", "Esrrb", "Sox2", "Lin28a",
              "Dnmt3a", "Cbx7", "Kdm2b", "Atf7ip2")
)
